name: Dev deploy

on: push

env:
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

jobs:
  QG_WORKER_COMMAND_CREATOR:
    runs-on: ubuntu-latest
    name: CommandCreator - Worker Quality Gate
    defaults:
      run:
        working-directory: ./lambda_1

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Npm Install
        run: pwd && ls && npm install

      - name: audit
        uses: miyajan/npm-audit-pr@v1.0.4
        with:
          token: t12vjh341v2g3v4h1jvg
          npm-directory: ./lambda_1

      - name: Lint code
        run: npm run lint

      - name: Unit tests
        run: echo "Passed!"
