name: Dev deploy

on: push

env:
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

jobs:
  QG_WORKER_COMMAND_CREATOR:
    runs-on: ubuntu-latest
    name: CommandCreator - Worker Quality Gate
    defaults:
      run:
        working-directory: ./lambda_1

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Npm Install
        run: pwd && ls && npm install

      - name: Running NPM audit
        uses: oke-py/npm-audit-action@v1.5.1
        with:
          audit_level: moderate
          github_token: ${{ secrets.GITHUB_TOKEN }}
          issue_assignees: oke-py
          issue_labels: vulnerability,test
          dedupe_issues: true
          working_directory: ./lambda_1

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@0.1.1
        env:
          SNYK_TOKEN: ${{ env.SNYK_TOKEN }}
        with:
          args: --all-projects

      - name: Lint code
        run: npm run lint

      - name: Unit tests
        run: echo "Passed!"
