name: Dev deploy

on: push

env:
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

jobs:
  QG_WORKER_COMMAND_CREATOR:
    runs-on: ubuntu-latest
    name: CommandCreator - Worker Quality Gate

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ env.SNYK_TOKEN }}
