name: Dev deploy

on:
  schedule:
    - cron: '* * * * *'
    branches:
      - master
jobs:
  QG_WORKER_COMMAND_CREATOR:
    runs-on: ubuntu-latest
    name: Cron - Running Audit
    defaults:
      run:
        working-directory: ./lambda_1

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Npm Install
        run: pwd && ls && npm install

      - name: audit
        uses: miyajan/npm-audit-pr@v1.0.4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          npm-directory: ./lambda_1

      - name: Unit tests
        run: echo "Passed!"
