name: Dev Deploy
on:
  push
jobs:
  QG_WORKER_COMMAND_CREATOR:
    runs-on: ubuntu-latest
    name: Cron - Running Audit

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          ref: master

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Npm Install
        working-directory: ./lambda_1
        run: pwd && ls && npm install

      - name: Listing Lambda 1
        run: ls

      - name: Listing directories
        working-directory: ./lambda_2
        run: ls
      
      - name: Showing
        run: npm run show

      - name: Back to Lambda 1
        working-directory: ./lambda_1
        run: npm run show
